language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"

install:
  - pip install .
before_script:
  - pip install requests nose mock coveralls
script: nosetests
after_success:
  - coveralls
