language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
  - "jython"

install:
  - pip install requests argparse nose mock coverage coveralls .
script: nosetests
#after_success:
#  - coveralls
