language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then 2to3 -w diffbot.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then 2to3 -w diffbot.py; fi
  - pip install requests nose mock coverage coveralls .
script:
  - nosetests
after_success:
  - coverage run --source=diffbot.py setup.py -q test
  - coveralls
